name: CI
on:
  push:
    branches: ["main"]

env:
  JABBA_INDEX: 'https://github.com/typelevel/jdk-index/raw/main/index.json'

jobs:
  run2021:
    strategy:
      fail-fast: true
      matrix:
        day: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: coursier/cache-action@v6      

      - uses: olafurpg/setup-scala@v13
        with:
          java-version: graalvm-ce-java17@21.3

      - name: Install Scala CLI
        run: | 
          curl -fL https://github.com/Virtuslab/scala-cli/releases/latest/download/scala-cli-x86_64-pc-linux.gz | gzip -d > scala-cli 
          chmod +x scala-cli

      - name: Run 
        run: ./scala-cli 2021/day${{ matrix.day }}.scala 2021/_lib.scala -- 2021/inputs/day${{ matrix.day }}-sample | tee results.txt

      - name: Validate result
        run: ./scala-cli validate.scala -- results.txt 2021 ${{ matrix.day }}
